# Generated by Django 4.0.5 on 2022-12-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_email_validation_user_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
