# Generated by Django 4.0.5 on 2023-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
