# Generated by Django 4.0.5 on 2023-01-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_deliver_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
