# Generated by Django 4.0.5 on 2023-01-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transactionId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
